import type { Metadata } from "next";
import { Frank_Ruhl_Libre, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const frankRuhi = Frank_Ruhl_Libre({
	weight: ["300", "700"],
	subsets: ["latin"],
	variable: "--font-frank-ruhi",
	display: "swap",
});
const lato = Lato({
	weight: ["100", "300", "400", "700", "900"],
	subsets: ["latin"],
	variable: "--font-lato",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Fifash | Nextjs",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${frankRuhi.variable} ${lato.variable} antialiased`}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
