import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Counters from "./_components/counters";
// import ProductSection from "./_components/isotop-product-filter";
import ProductSlider from "./_components/product-slider";
import ReviewsSlider from "./_components/reviews-slider";
import DealOfTheDay from "./_components/deal-section";
import dynamic from "next/dynamic";
const ProductSection = dynamic(
	() => import("./_components/isotop-product-filter"),
	{ ssr: false }
);

export const metadata: Metadata = {
	title: "Fifash | Home",
	description: "Generated by create next app",
};

export default function Home() {
	return (
		<main>
			<section className="bg-section_bg pt-10 md:pt-28 pb-10 md:pb-32">
				<div className="container flex flex-col md:flex-row relative">
					{/* Left Text Section */}
					<div className="w-full md:w-1/2 order-2 md:order-1 text-center md:text-start relative">
						<h1 className="text-4xl sm:text-5xl lg:text-6xl lg:leading-11 font-bold md:max-w-[448px] capitalize">
							Find the best fashion style for you
						</h1>
						<p className="text-base leading-7 font-bold md:max-w-[468px] mt-space-5.22 mb-space-7.22">
							Lorem Ipsum is simply dummy text of the printing and
							typesetting industry. Lorem Ipsum has been the industry's
							standard dummy text ever since the 1500s, when an unknown
							printer took a galley of type and scrambled it to make a
							type specimen book.
						</p>
						<button className="py-6 px-24 rounded-lg text-base leading-5 bg-primary text-secondary_white relative z-20">
							Shop Now
						</button>
					</div>

					{/* Right Image Section */}
					<div className="w-4/5 md:w-1/2 m-auto order-1 md:order-2 relative z-20 max-md:mb-6">
						<Image
							src="/img/abatar-1.png"
							alt="Avatar"
							width={645}
							height={630}
							priority
						/>
						<Image
							className="absolute bottom-4 -left-10 z-30"
							src="/img/abarar-bg.png"
							alt="Background Decoration"
							width={124}
							height={127}
							priority
						/>
					</div>

					{/* Decorative Elements */}
					<div className="w-[19.930%] aspect-square bg-gray_bg/35 absolute -bottom-10 md:-bottom-32 left-0 z-10"></div>
					<Image
						className="absolute top-8 right-5 z-30"
						src="/img/abarar-bg.png"
						alt="Top Decoration"
						width={124}
						height={127}
						priority
					/>
				</div>
			</section>

			{/* new collection */}
			<section className="mt-10 md:mt-24 overflow-hidden">
				<div className="container">
					<div className="text-center">
						<h2 className="text-5xl md:text-6xl md:leading-11 font-bold mb-8 capitalize">
							new collection
						</h2>
						<p className="text-base leading-7 font-bold">
							when an unknown printer took a galley of type and scrambled
							it to make a type specimen book.
						</p>
					</div>
					<div className="relative mt-12">
						<Image
							className="absolute -bottom-4 -left-12 pointer-events-none"
							src="/img/abarar-bg.png"
							alt="abatar"
							width={124}
							height={127}
						/>
						<Image
							className="absolute -top-8 -right-12 pointer-events-none"
							src="/img/abarar-bg.png"
							alt="abatar"
							width={124}
							height={127}
						/>
						<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-7 relative ">
							<figure className="relative">
								<Image
									className="w-full"
									src="/img/abatar-2.jpg"
									alt="abatar img"
									width={411}
									height={490}
								/>
								<figcaption>
									<Link
										href="#"
										className="py-5 bg-secondary_white text-center absolute bottom-4 md:bottom-6 left-5 md:left-10 right-5 md:right-10 rounded-lg">
										SWEATER
									</Link>
								</figcaption>
							</figure>
							<figure className="relative">
								<Image
									className="w-full"
									src="/img/abatar-3.jpg"
									alt="abatar img"
									width={411}
									height={490}
								/>
								<figcaption>
									<Link
										href="#"
										className="py-5 bg-secondary_white text-center absolute bottom-4 md:bottom-6 left-5 md:left-10 right-5 md:right-10 rounded-lg">
										SWEATER
									</Link>
								</figcaption>
							</figure>
							<figure className="relative">
								<Image
									className="w-full"
									src="/img/abatar-4.jpg"
									alt="abatar img"
									width={411}
									height={490}
								/>
								<figcaption>
									<Link
										href="#"
										className="py-5 bg-secondary_white text-center absolute bottom-4 md:bottom-6 left-5 md:left-10 right-5 md:right-10 rounded-lg">
										SWEATER
									</Link>
								</figcaption>
							</figure>
						</div>
					</div>
				</div>
			</section>

			{/* Overview */}
			<section className="mt-14 md:mt-28 mb-20">
				<div className="container relative">
					<div className="flex flex-col md:flex-row gap-[7.441%] justify-center items-center">
						<div className="w-4/5 md:w-1/2 order-2 md:order-1 relative">
							<div className="w-[27.272%] bg-section_bg/80 absolute -bottom-7 -left-4 aspect-square" />
							<Image
								className="absolute -top-4 -right-16"
								src="/img/abarar-bg.png"
								alt="abatar"
								width={124}
								height={127}
							/>
							<Image
								className="w-full"
								src="/img/abatar-5.jpg"
								alt="abatar img"
								width={597}
								height={687}
							/>
						</div>
						<div className="w-4/5 md:w-1/2 order-1 md:order-2 text-center md:text-left mb-10">
							<h2 className="text-5xl lg:text-6xl lg:leading-11 font-bold md:max-w-[402px] mb-5">
								BEST Fashion Since 2022
							</h2>
							<p className="text-base leading-8 font-bold md:max-w-[467px]">
								Lorem Ipsum is simply dummy text of the printing and
								typesetting industry. Lorem Ipsum has been the
								industry's standard dummy text ever since the 1500s,
								when an unknown printer took a galley of type and
								scrambled it to make a type specimen book. It has
								survived not only five centuries, but also the leap into
								electronic typesetting, remaining essentially unchanged.
							</p>
						</div>
					</div>
					<Counters />
				</div>
			</section>

			{/* bestseller */}
			<section className="mt-8 md:mt-16 lg:mt-32 bg-primary overflow-hidden">
				<div className="container py-10 md:py-20">
					<div className="flex items-center flex-col md:flex-row">
						<div className="w-full md:w-[420px] md:pr-7 mb-10 md:mb-0 text-center md:text-start">
							<h2 className="text-5xl xl:text-6xl xl:leading-11 font-bold text-secondary_white mb-3 capitalize">
								best seller product
							</h2>
							<p className="text-base leading-7.2 font-bold text-secondary_white">
								Lorem Ipsum is simply dummy text of the printing and
								typesetting industry. Lorem Ipsum has been the
								industry's standard dummy text ever since the 1500s,
								when an unknown printer took a galley of type and
								scrambled it to make a type specimen book. It has
								survived not only five centuries, .
							</p>
							<button className="py-5 px-16 xl:px-24 rounded-lg text-base leading-5 bg-primary text-secondary_white relative z-20 border border-secondary_white mt-9">
								see more
							</button>
						</div>
						<div className="w-full md:w-[calc(100%-420px)]">
							<ProductSlider />
						</div>
					</div>
				</div>
			</section>

			{/* Products */}
			<ProductSection />

			{/* deal */}
			<DealOfTheDay />

			{/* reviews */}
			<section className="pb-10 sm:pb-16 md:pb-32">
				<div className=" text-center mb-16">
					<h2 className="text-5xl md:text-6xl md:leading-11 font-bold mb-8 capitalize">
						what people say about us
					</h2>
					<p className="text-base leading-7 font-bold">
						when an unknown printer took a galley of type and scrambled it
						to make a type specimen book.
					</p>
				</div>
				<div className="container">
					<ReviewsSlider />
				</div>
			</section>

			{/* instagram feed */}
			<section className="relative">
				<div className="container">
					<div
						className="grid grid-cols-3 md:grid-cols-5"
						id="scrollable_items">
						<Image
							src="/img/abatar-17.jpg"
							alt="abatar"
							width={288}
							height={389}
							className="object-cover w-full"
						/>
						<Image
							src="/img/abatar-18.jpg"
							alt="abatar"
							width={288}
							height={389}
							className="object-cover w-full"
						/>
						<Image
							src="/img/abatar-19.jpg"
							alt="abatar"
							width={288}
							height={389}
							className="object-cover w-full"
						/>
						<Image
							src="/img/abatar-20.jpg"
							alt="abatar"
							width={288}
							height={389}
							className="object-cover w-full"
						/>
						<Image
							src="/img/abatar-21.jpg"
							alt="abatar"
							width={288}
							height={389}
							className="object-cover w-full"
						/>
					</div>
				</div>
				<div className="w-[542px] max-w-8xl py-5 md:py-9 px-7 md:px-14 bg-secondary_white absolute -bottom-12 left-1/2 -translate-x-1/2 z-30 text-center">
					<h4 className="text-base sm:text-lg md:text-xl md:leading-7.2 font-lato font-black text-black uppercase">
						follow our instagram:@fifash trends
					</h4>
				</div>
			</section>
		</main>
	);
}
