import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
	title: "Fifash | Home",
	description: "Generated by create next app",
};

export default function Home() {
	return (
		<main>
			<section className="bg-section_bg pt-10 md:pt-28 pb-10 md:pb-32">
				<div className="container mx-auto px-4 lg:px-space-x-18 flex flex-col md:flex-row relative">
					{/* Left Text Section */}
					<div className="w-full md:w-1/2 order-2 md:order-1 text-center md:text-start relative">
						<h1 className="text-4xl sm:text-5xl lg:text-6xl lg:leading-11 font-bold md:max-w-[448px] capitalize">
							Find the best fashion style for you
						</h1>
						<p className="text-base leading-7 font-bold md:max-w-[468px] mt-space-5.22 mb-space-7.22">
							Lorem Ipsum is simply dummy text of the printing and
							typesetting industry. Lorem Ipsum has been the industry's
							standard dummy text ever since the 1500s, when an unknown
							printer took a galley of type and scrambled it to make a
							type specimen book.
						</p>
						<button className="py-6 px-24 rounded-lg text-base leading-5 bg-primary text-secondary_white relative z-20">
							Shop Now
						</button>
					</div>

					{/* Right Image Section */}
					<div className="w-4/5 md:w-1/2 m-auto order-1 md:order-2 relative z-20">
						<Image
							src="/img/abatar-1.png"
							alt="Avatar"
							width={645}
							height={630}
							priority
						/>
						<Image
							className="absolute bottom-4 -left-10 z-30"
							src="/img/abarar-bg.png"
							alt="Background Decoration"
							width={124}
							height={127}
							priority
						/>
					</div>

					{/* Decorative Elements */}
					<div className="w-[19.930%] aspect-square bg-gray_bg/35 absolute -bottom-10 md:-bottom-32 left-0 z-10"></div>
					<Image
						className="absolute top-8 right-5 z-30"
						src="/img/abarar-bg.png"
						alt="Top Decoration"
						width={124}
						height={127}
						priority
					/>
				</div>
			</section>
		</main>
	);
}
